### ISSUE TITLE
Pipelines as Code Proposal

### ISSUE THREAD

**Issue by clintberry** [ploio/ploio#1]
After playing with several different methods of creating pipelines as code, I settled on this first proposal. In an effort to keep deployments simple, I settled on the following items:

- Stick with YAML for config as it matches Kubernetes and the ecosystem as a whole
- Use a pipeline templating system so it is easy to get started and re-use pipelines, but also flexible for more advanced usage
- Use spinnaker syntax where appropriate so it is easy for those wanting to transition or that are familiar with that syntax already

Here is an example pipeline template for a simple deploy to a k8s cluster, then a manual check to verify it is working:

```yaml
---
schema: "1"
id: "deployManualCheck"
metadata:
  name: "Deploy and Manual Check"
  description: "Deploy to a cluster and then wait for a manual approval"
variables:
- name: clusterID
- name: namespace
- name: replicas
  default: 1
- name: memory
  required: false
- name: cpu
  required: false

stages:
- id: deploy
  type: deploy
  name: "Deploy to {{ clusterID }}"
  cluster: "{{ clusterID }}"
  replicas: "{{ replicas }}" 
  strategy: "rolling"
  namespace: "{{ namespace }}"
  memory: "{{ memory }}"
  cpu: "{{ cpu }}"

- id: check
  name: "Manual Check"
  strategy: manual
  dependsOn: deploy
```

Notice that the variables section is very similar to Spinnaker's. Just declare variables and thier names. You can also specify a `default` value for the variable and it defaults to `requires: true` unless a default is set or you overwrite the required setting to `false`

The stages section for this template is fairly straight forward. It uses Go templates to fill in the variables where they go and is restricted to much less configuration than a standard kubernetes deployment. Things like Liveness and Readiness probe, and services exist on the application level (see sample config for an application below). This initial sample uses a "rolling" strategy but as we progress with istio we will add `canary` and `smoke` strategies as well. There are many other settings to consider including `autoScaling`.

Notice the use of `dependsOn` for the second stage in the pipeline. That is copied from the spinnaker config. It allows concurrent stages to be executed at the same time if they both have the same dependsOn.

This template config would be added to Ploio and available on the server, or could also be referenced to as a local file in the same repo.

Here is a sample application config:

```yaml
schema: "1"

id: bart
name: bart
owner: "clint@getweave.com"
repo: "weavelab/bart"

services:
- name: bart-service
  type: node-port 
  ports:
  - name: "grpc"
    protocol: "TCP"
    nodePort: "36011"
    port: "80"
    targetPort: "9000"

env:
- name: "LISTEN_PORT"
  type: "value"
  value: "9000"

pipeline:
  name: "Deploy to Dev"
  template: deploy-manual-check
  variables:
    clusterID: dev-ut
    namespace: phone
stages: []
```

First it starts with its metadata (name, ID, owner, repo) and then it also has a section for services and environment variables. This is an abstraction of the kubernetes config since the kubernetes config was never intended to be built by hand in the first place (https://blog.heptio.com/ksonnet-intro-43f6183a97a6).

Then the pipeline section gets a name, chooses a template to work from, and then gives values to all the required variables. You can also overwrite stages by adding manual stages to the stages array. 

This is very early but I wanted to get it out there for feedback.
